services:
  - type: web
    name: itsnisuxyz
    runtime: node
    branch: trunk
    startCommand: bun .output/server/index.mjs
    buildCommand: pnpm install && pnpm run build
    envVars:
      - key: NITRO_PRESET
        value: render_com
